# Project
include_guard(GLOBAL)

# Vcpkg
find_program(VCPKG NAMES vcpkg REQUIRED)
get_filename_component(VCPKG_ROOT ${VCPKG} DIRECTORY)

if(DEFINED ENV{VCPKG_CACHE})
    file(TO_CMAKE_PATH "$ENV{VCPKG_CACHE}" VCPKG_CACHE)
else()
    set(VCPKG_CACHE "${CMAKE_SOURCE_DIR}/.cache" CACHE PATH "")
endif()

set(VCPKG_APPLOCAL_DEPS OFF)
set(VCPKG_HOST_TRIPLET ${VCPKG_TARGET_TRIPLET})
set(VCPKG_INSTALL_OPTIONS "--x-no-default-features")
set(VCPKG_INSTALL_OPTIONS "${VCPKG_INSTALL_OPTIONS};--no-print-usage")
set(VCPKG_INSTALL_OPTIONS "${VCPKG_INSTALL_OPTIONS};--clean-packages-after-build")
set(VCPKG_INSTALL_OPTIONS "${VCPKG_INSTALL_OPTIONS};--overlay-ports=${CMAKE_CURRENT_LIST_DIR}/ports")
set(VCPKG_INSTALL_OPTIONS "${VCPKG_INSTALL_OPTIONS};--overlay-triplets=${CMAKE_CURRENT_LIST_DIR}/triplets")
set(VCPKG_INSTALL_OPTIONS "${VCPKG_INSTALL_OPTIONS};--x-buildtrees-root=${VCPKG_CACHE}/buildtrees")
set(VCPKG_INSTALL_OPTIONS "${VCPKG_INSTALL_OPTIONS};--x-downloads-root=${VCPKG_CACHE}/downloads")
set(VCPKG_INSTALL_OPTIONS "${VCPKG_INSTALL_OPTIONS};--x-packages-root=${VCPKG_CACHE}/packages")
set(VCPKG_INSTALLED_DIR "${VCPKG_CACHE}/installed/${VCPKG_TARGET_TRIPLET}")

set(ENV{PKG_CONFIG_PATH} "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/pkgconfig")
set(PKG_CONFIG_USE_CMAKE_PREFIX_PATH ON CACHE BOOL "")

if(NOT DEFINED ENV{VCPKG_BINARY_SOURCES})
    set(ENV{VCPKG_BINARY_SOURCES} "clear;files,${VCPKG_CACHE}/binaries,readwrite")
endif()

set(ENV{VCPKG_FORCE_SYSTEM_BINARIES} "0")

set(ENV{VCPKG_DISABLE_METRICS} "1")
include("${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake")

# Modules
list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR}/cmake)
list(APPEND CMAKE_PREFIX_PATH ${VCPKG_INSTALLED_DIR})
list(APPEND CMAKE_PREFIX_PATH ${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET})
list(APPEND CMAKE_PREFIX_PATH ${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib)
list(APPEND CMAKE_PREFIX_PATH ${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/pkgconfig)

# Standard
set(CMAKE_CXX_STANDARD 23 CACHE STRING "")
set(CMAKE_CXX_EXTENSIONS OFF CACHE BOOL "")
set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE BOOL "")

# Search Path
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SOURCE_DIR}/res/cmake;${VCPKG_INSTALLED_DIR}")
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY CACHE STRING "" FORCE)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY CACHE STRING "" FORCE)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY CACHE STRING "" FORCE)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH CACHE STRING "" FORCE)
set(CMAKE_FIND_PACKAGE_PREFER_CONFIG ON CACHE BOOL "" FORCE)

# Build Directories
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib/$<CONFIG>")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib/$<CONFIG>")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<CONFIG>")
set(CMAKE_PDB_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<CONFIG>")

# Variables
if(CMAKE_TOOLCHAIN_FILE)
    mark_as_advanced(CMAKE_TOOLCHAIN_FILE)
endif()
if(CMAKE_VERBOSE_MAKEFILE)
    mark_as_advanced(CMAKE_VERBOSE_MAKEFILE)
endif()
if(CMAKE_EXPORT_COMPILE_COMMANDS)
    mark_as_advanced(CMAKE_EXPORT_COMPILE_COMMANDS)
endif()
