file(GLOB_RECURSE EXAMPLES ${CMAKE_CURRENT_SOURCE_DIR}/examples/*.cpp)
set(COUSB_EXAMPLES example)
set(COUSB_EXAMPLES_FLAGS "-static")
foreach(example_path IN LISTS EXAMPLES)
  get_filename_component(fname "${example_path}" NAME)
  get_filename_component(target_name "${fname}" NAME_WE)
  set(EXAMPLE "${COUSB_EXAMPLES}-${target_name}")
  add_executable(${EXAMPLE} "${example_path}")
  target_link_libraries(${EXAMPLE} PRIVATE ${PROJECT_NAME} -static)
  set_target_properties(${EXAMPLE} PROPERTIES CXX_STANDARD 23)
endforeach()
