name: Build and deploy Doxygen

on:
  push:
    branches: [ master ]

jobs:
  doxygen:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Run Doxygen
        run: |
          ROOT=$(pwd)
          PRESET=no-vcpkg
          rm -rf build/$PRESET
          cmake --preset $PRESET -DCOUSB_ONLY_BUILD_DOCS=ON
          cmake --build build/$PRESET --target docs 1>/dev/null
          mkdir -p docs/html
          cp $ROOT/build/$PRESET/docs/html/* $ROOT/docs/html -r
          echo "Finished building docs"

      - name: Prepare nojekyll
        run: touch docs/html/.nojekyll

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          publish_branch: gh-pages
