name: Build and run tests

on:
  push:
    branches: [ dev, master ]

jobs:
  doxygen:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git cmake gcc libusb-1.0-0-dev

      - name: Install vcpkg
        run: git clone https://github.com/vcpkg/vcpkg && ./vcpkg/bootstrap-vcpkg.sh

      - name: Run cmake
        run: VCPKG_ROOT=$(pwd)/vcpkg ./setup.sh x64-static Debug

      - name: Run test
        run: cd build/x64-static && ctest -V -R .
